language: php
dist: bionic

php:
  - 7.4

before_script:
  - sudo apt-get update
  - sudo apt -y install software-properties-common
  - apt-get install -y language-pack-en-base && export LC_ALL=en_US.UTF-8 && export LANG=en_US.UTF-8 &&
  - sudo add-apt-repository ppa:ondrej/php
  - sudo apt-get -y install php7.4-ffi
  - echo "extension = ffi.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini