language: php
php:
  - 7.4

before_script:
  - sudo apt-get update
  - sudo apt-get -y install php7.4-ffi
  - echo "extension = ffi.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: composer install