name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amaccis/php-libstemmer:2.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit