name: CI

on:
  pull_request: ~
  push:
    branches:
      - master
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amaccis/php-libstemmer:2.0.0
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v3