name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    concurrency:
      group: testing_environment
      cancel-in-progress: true

    strategy:
      matrix:
        container:
          - "amaccis/php-libstemmer:8.1.31-2.2.0"
          - "amaccis/php-libstemmer:8.2.27-2.2.0"
          - "amaccis/php-libstemmer:8.3.15-2.2.0"
          - "amaccis/php-libstemmer:8.4.2-2.2.0"

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit
      - name: Run static analysis
        run: vendor/bin/phpstan