name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        container:
          - "amaccis/php-libstemmer:8.1.32-3.0.0"
          - "amaccis/php-libstemmer:8.2.28-3.0.0"
          - "amaccis/php-libstemmer:8.3.20-3.0.0"
          - "amaccis/php-libstemmer:8.4.6-3.0.0"

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit
      - name: Run static analysis
        run: vendor/bin/phpstan