name: CI

on:
  pull_request: ~
  push:
    branches:
      - master
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    container: amaccis/php-libstemmer:2.0.0
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: composer install
        uses: composer install

